
name: 'MPLAB XC32 Build Action'
description: 'Build MPLAB XC32 project inside Docker container'

inputs:
  project:
    description: 'Path to MPLAB-X project'
    required: true
  configuration:
    description: 'Configuration name'
    required: true
  packs:
    description: 'DFP/ CMSIS Packs'
    required: false
    default: ""

runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.configuration }}
    - ${{ inputs.packs }}
